environment:
  version_suffix: alpha
  nuget_api_key: hCYZb1qY+PIMKQZ21VS2lkCBSvrEUzFvEXrV/mTmpa+f5DDh4YtGowrmOAhpVrD7
  
version: 1.0.{build}-$(version_suffix)

# branches to build
branches:
  only:
  - master

image: Visual Studio 2017

configuration: Release

# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

# restore Nuget packages before build:
before_build:
- nuget restore

build:
  publish_nuget: true # package projects with .nuspec files and push to artifacts
  #publish_nuget_symbols: true # generate and publish NuGet symbol packages
  verbosity: minimal

artifacts:
 - path: '**\*.nupkg'
# - path: DbExecutor.Abstract\bin\$(configuration)\**\*.nupkg

deploy:
 - provider: NuGet
   name: production
   server: 
   api_key:
    secure: hCYZb1qY+PIMKQZ21VS2lkCBSvrEUzFvEXrV/mTmpa+f5DDh4YtGowrmOAhpVrD7 #'{nuget_api_key}'
   skip_symbols: true
   artifact: /.*\.nupkg/

# Deploy to GitHub Releases
# - provider: GitHub
#   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                # release from master branch only
#     appveyor_repo_tag: true       # deploy on tag push only 
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: builds
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true