environment:
  version_suffix: alpha
  
version: 1.0.0-$(version_suffix){build}

# branches to build
branches:
  except:
  - master

image: Visual Studio 2017

configuration: Release

# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

# restore Nuget packages before build:
before_build:
- nuget restore

build:
  publish_nuget: true # package projects with .nuspec files and push to artifacts
  #publish_nuget_symbols: true # generate and publish NuGet symbol packages
  verbosity: minimal

artifacts:
 - path: '**\*.nupkg'

deploy:
 - provider: NuGet
   name: dev
   server: https://ci.appveyor.com/nuget/valeriy1991 # remove to push to NuGet.org
   api_key:
    secure: m9mXfgL3RpGeznuLZm94nyhU7+Awk2jr5eddNy8Sw8Y=
   skip_symbols: true
   artifact: /.*\.nupkg/
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: builds
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true